version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: gophermart-db
    restart: always
    environment:
      POSTGRES_USER: gophermart
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: gophermart
    ports:
      - "5432:5432"
    volumes:
      - gophermart_pgdata:/var/lib/postgresql/data

volumes:
  gophermart_pgdata:
